Repository LastExTrascendence/backend, pull requests merged in 2023-12, with the labels that each got.

#8 feat: otp, otp on, off 기능 추가 #7
  package-lock.json
  package.json
  src/auth/auth.controller.ts
  src/auth/auth.guard.ts
  src/auth/auth.service.ts
  src/auth/dto/auth-credential.dto.ts
  src/auth/strategy/jwt.strategy.ts
  src/auth/strategy/oauth.strategy.ts
  src/user/user.controller.ts
  src/user/user.module.ts
  src/user/user.service.ts
Labels: Feat

#9 feat: 작동하지 않는 otp 기능 주석처리 #7
  src/auth/auth.controller.ts
  src/auth/auth.service.ts
Labels: bug

#10 feat: oauth res cookie, 부분 개선 #7
  package-lock.json
  package.json
  src/auth/auth.controller.ts
  src/auth/auth.module.ts
  src/auth/auth.service.ts
  src/auth/dto/auth-credential.dto.ts
  src/auth/strategy/jwt.strategy.ts
  src/auth/strategy/oauth.strategy.ts
  src/channel/channel.gateway.spec.ts
  src/channel/channel.gateway.ts
  src/channel/channel.module.ts
  src/channel/channel.service.ts
  src/configs/typeorm.config.ts
  src/dm/dm.gateway.ts
  src/dm/dm.module.ts
  src/dm/dm.service.ts
  src/dm/dto/dm.dto.ts
  src/dm/entity/dm.entity.ts
  src/user/dto/user.dto.ts
  src/user/entity/user.blocked.entity.ts
  src/user/entity/user.entity.ts
  src/user/entity/user.enum.ts
  src/user/entity/user.friends.entity.ts
  src/user/user.controller.ts
  src/user/user.module.ts
  src/user/user.service.ts
Labels: Feat

#11 feat: user, block 과 friend에 add, find, remove 기능 추가
  src/auth/auth.controller.ts
  src/auth/auth.service.ts
  src/configs/typeorm.config.ts
  src/dm/dm.gateway.ts
  src/dm/dm.module.ts
  src/dm/dto/dm.dto.ts
  src/dm/entity/dm.entity.ts
  src/user/dto/user.dto.ts
  src/user/entity/user.blocked.entity.ts
  src/user/entity/user.friends.entity.ts
  src/user/user.avatar.service.ts
  src/user/user.block.service.ts
  src/user/user.controller.ts
  src/user/user.friend.service.ts
  src/user/user.module.ts
  src/user/user.repository.ts
  src/user/user.service.ts
Labels: Feat

#14 fix: user, create 시 db에 담길 떄 status가 null로 설정되는 문제 수정
  package-lock.json
  package.json
  src/user/user.controller.ts
  src/user/user.service.ts
Labels: fix

#17 fix: user 테이블 ERD 수정, 백앤드 User 로직 최적화 및 UserDto 수정 #16
  src/auth/auth.controller.ts
  src/auth/auth.service.ts
  src/auth/strategy/jwt.strategy.ts
  src/auth/strategy/oauth.strategy.ts
  src/configs/typeorm.config.ts
  src/dm/entity/dm.entity.ts
  src/user/dto/user.dto.ts
  src/user/entity/user.block.entity.ts
  src/user/entity/user.blocked.entity.ts
  src/user/entity/user.entity.ts
  src/user/entity/user.enum.ts
  src/user/entity/user.friend.entity.ts
  src/user/entity/user.friends.entity.ts
  src/user/user.avatar.service.ts
  src/user/user.block.service.ts
  src/user/user.controller.ts
  src/user/user.friend.service.ts
  src/user/user.module.ts
  src/user/user.service.ts
Labels: bug, enhancement

#19 feat: Dm 과 Channel 기능 병합, Channel User DB 기능 추가
  package-lock.json
  package.json
  src/app.controller.ts
  src/app.module.ts
  src/channel/channel.enum.ts
  src/channel/channel.gateway.spec.ts
  src/channel/channel.gateway.ts
  src/channel/channel.module.ts
  src/channel/channel.service.ts
  src/channel/channel.user.repositroy.ts
  src/channel/channel.user.service.ts
  src/channel/channel_dto/channel.user.dto.ts
  src/channel/channel_dto/channels.dto.ts
  src/channel/channel_entity/channel.user.entity.ts
  src/channel/channel_entity/channels.entity.ts
  src/channel/channels.repository.ts
  src/channel/socket/socket.module.ts
  src/channel/socket/socket_client.ts
  src/configs/typeorm.config.ts
  src/dm/dm.gateway.ts
  src/dm/dm.module.ts
  src/main.ts
  static/index.html
  static/jaeyojun.index.html
  static/yeomin.index.html
Labels: Feat

#20 fix: user, userDto, 누락된 id:number 추가
  package-lock.json
  src/channel/socket/socket_client.ts
  src/redis/redis.adapter.ts
  src/user/dto/user.dto.ts
  src/user/user.controller.ts
  src/user/user.service.ts
Labels: fix

#22 feat: user, user friend 존재 시 친구 여부와 친구 생성 시간 정보 기능 추가
  src/app.module.ts
  src/configs/typeorm.config.ts
  src/dm/dm.gateway.ts
  src/game/dto/game.dto.ts
  src/game/entity/game.entity.ts
  src/game/entity/game.enum.ts
  src/game/entity/game.players.entity.ts
  src/game/game.controller.ts
  src/game/game.module.ts
  src/game/game.players.service.ts
  src/game/game.service.ts
  src/user/dto/user.profile.dto.ts
  src/user/user.controller.ts
  src/user/user.friend.service.ts
  src/user/user.module.ts
  src/user/user.service.ts
Labels: Feat

#24 refactor: user, user controller 데코레이터 구조 변경
  src/auth/auth.service.ts
  src/dm/dm.gateway.ts
  src/user/user.avatar.service.ts
  src/user/user.block.service.ts
  src/user/user.controller.ts
  src/user/user.friend.service.ts
  src/user/user.service.ts
Labels: refactor

#25 feat: chat, Dm, 채팅 내역을 가져올 수 있는 getRedis 기능 추가
  src/configs/typeorm.config.ts
  src/dm/dm.gateway.ts
  src/dm/dm.module.ts
  src/dm/dm.service.ts
  src/dm/dm_channels.repository.ts
  src/dm/dto/dm.channels.dto.ts
  src/dm/dto/dm.dto.ts
  src/dm/dto/dm.user.dto.ts
  src/dm/entity/dm.channels.entity.ts
  src/dm/entity/dm.user.entity.ts
Labels: Feat
