Repository LastExTrascendence/backend, pull requests merged in 2024-01, with the labels that each got.

#26 feat: game, user enter, leave, T/O 등 기능 추가
  src/auth/auth.controller.ts
  src/auth/auth.service.ts
  src/auth/dto/twofa.dto.ts
  src/channel/channels.repository.ts
  src/game/game.gateway.ts
  src/user/user.avatar.service.ts
  src/user/user.controller.ts
  src/user/user.module.ts
  src/user/user.repository.ts
Labels: Feat

#27 feat: channel, game DTO 대격변
  package-lock.json
  package.json
  src/channel/channel.controller.ts
  src/channel/channel.gateway.ts
  src/channel/channel.module.ts
  src/channel/channel.service.ts
  src/channel/channel.user.repositroy.ts
  src/channel/channel.user.service.ts
  src/channel/channel_dto/channels.dto.ts
  src/channel/socket/socket.module.ts
  src/game/game.controller.ts
  src/game/game.gateway.ts
  src/game/game.module.ts
  src/game/game.service.ts
Labels: Feat

#28 feat: channel, game, list 조회 기능 추가
  src/channel/channel.controller.ts
  src/channel/channel.service.ts
  src/game/dto/game.dto.ts
  src/game/entity/game.enum.ts
  src/game/game.controller.ts
  src/game/game.service.ts
Labels: Feat

#30 feat: channel, create 후 channel, channeluser db 저장 기능 추가
  src/channel/channel.controller.ts
  src/channel/channel.gateway.ts
  src/channel/channel.module.ts
  src/channel/channel.service.ts
  src/channel/channel_dto/channel.user.dto.ts
  src/channel/channel_dto/channels.dto.ts
  src/channel/channel_entity/channels.entity.ts
Labels: Feat

#31 fix: 로그인 방식, Strategy, Guard 전면 수정 및 리팩토링 #18
  package-lock.json
  package.json
  src/app.controller.spec.ts
  src/app.controller.ts
  src/app.module.ts
  src/app.service.ts
  src/auth/auth.controller.ts
  src/auth/auth.guard.ts
  src/auth/auth.module.ts
  src/auth/auth.service.ts
  src/auth/fortytwo/fortytwo.guard.ts
  src/auth/fortytwo/fortytwo.strategy.ts
  src/auth/jwt/jwt.strategy.ts
  src/auth/jwt/jwtAuth.guard.ts
  src/auth/jwt/jwtSign.guard.ts
  src/auth/jwt/jwtUserCreation.guard.ts
  src/auth/strategy/jwt.strategy.ts
  src/channel/channel.controller.ts
  src/channel/channel.gateway.ts
  src/channel/channel.module.ts
  src/configs/typeorm.config.ts
  src/decorator/user.decorator.ts
  src/dm/dm.gateway.ts
  src/dm/dm.module.ts
  src/game/game.controller.ts
  src/game/game.gateway.ts
  src/game/game.module.ts
  src/main.ts
  src/middleware/middleware.d.ts
  src/middleware/session-middleware.ts
  src/user/dto/user.dto.ts
  src/user/dto/user.profile.dto.ts
  src/user/entity/user.entity.ts
  src/user/entity/user.enum.ts
  src/user/user.controller.ts
  src/user/user.module.ts
  src/user/user.service.ts
Labels: enhancement, Feat, fix

#32 fix: channel, auth merge 에 대한 충돌 이슈
  src/channel/channel.controller.ts
  src/channel/channel.enum.ts
  src/channel/channel.gateway.ts
  src/channel/channel.module.ts
  src/channel/channel.service.ts
  src/channel/channel_dto/channel.user.dto.ts
  src/channel/channel_dto/channels.dto.ts
  src/channel/channel_entity/channel.user.entity.ts
  src/channel/channel_entity/channels.entity.ts
Labels: fix

#33 fix: channel, merge에 인한 get요청 수정
  src/channel/channel.controller.ts
  src/channel/channel.service.ts
  src/channel/channel_entity/channels.entity.ts
Labels: fix

#36 feat: channel, gateway ban, kick, changeRole 현재유저 정보 반환 기능 추가
  src/auth/auth.controller.ts
  src/auth/auth.module.ts
  src/auth/auth.service.ts
  src/channel/channel.controller.ts
  src/channel/channel.gateway.spec.ts
  src/channel/channel.gateway.ts
  src/channel/channel.module.ts
  src/channel/channel.service.ts
  src/channel/channel.user.repositroy.ts
  src/channel/channel.user.service.ts
  src/channel/channel_dto/channel.user.dto.ts
  src/channel/channel_dto/channels.dto.ts
  src/channel/channel_entity/channel.user.entity.ts
  src/channel/channel_entity/channels.entity.ts
  src/channel/channels.repository.ts
  src/dm/dm.gateway.ts
  src/dm/dm.module.ts
  src/dm/dm.service.ts
  src/dm/dm_channels.repository.ts
  src/dm/dto/dm.dto.ts
  src/user/user.service.ts
Labels: Feat

#37 feat: OTP 기능 구현
  qr-codes/1_qrcode.png
  src/auth/auth.controller.ts
  src/auth/auth.service.ts
  src/channel/channel.controller.ts
  src/channel/channel.gateway.ts
  src/channel/channel.service.ts
  src/channel/channel_entity/channels.entity.ts
  src/dm/dm.gateway.ts
  src/user/dto/user.dto.ts
Labels: Feat

#39 feat: game, game API, game gateway 기능 다수 추가
  package-lock.json
  package.json
  src/auth/auth.controller.ts
  src/auth/auth.service.ts
  src/auth/dto/twofa.dto.ts
  src/channel/channel.controller.ts
  src/channel/channel.gateway.ts
  src/channel/channel.module.ts
  src/channel/channel.service.ts
  src/channel/channel_dto/channel.user.dto.ts
  src/channel/channel_dto/channels.dto.ts
  src/channel/dto/channel.user.dto.ts
  src/channel/dto/channels.dto.ts
  src/channel/entity/channel.user.entity.ts
  src/channel/entity/channels.entity.ts
  src/channel/enum/channel.enum.ts
  src/configs/typeorm.config.ts
  src/dm/dm.gateway.ts
  src/dm/dm.module.ts
  src/dm/dm.service.ts
  src/dm/dm_channels.repository.ts
  src/dm/dto/dm.channels.dto.ts
  src/dm/dto/dm.dto.ts
  src/dm/dto/dm.user.dto.ts
  src/dm/entity/dm.channels.entity.ts
  src/dm/entity/dm.user.entity.ts
  src/game/dto/game.dto.ts
  src/game/entity/game.entity.ts
  src/game/entity/game.players.entity.ts
  src/game/enum/game.enum.ts
  src/game/game.controller.ts
  src/game/game.gateway.ts
  src/game/game.module.ts
  src/game/game.players.service.ts
  src/game/game.service.ts
  src/user/user.controller.ts
  src/user/user.module.ts
  src/user/user.service.ts
Labels: Feat

#41 fix: kick, ban, mute 미작동 부분 개선
  src/channel/channel.controller.ts
  src/channel/channel.gateway.ts
  src/channel/channel.module.ts
  src/channel/channel.service.ts
  src/channel/entity/channel.user.entity.ts
  src/dm/dm.gateway.ts
  src/game/game.gateway.ts
  src/game/game.module.ts
  src/game/game.service.ts
Labels: Feat, fix

#46 feat: user, UserOtpSecret Entity 생성
  src/app.module.ts
  src/channel/channel.gateway.ts
  src/channel/channel.service.ts
  src/configs/typeorm.config.ts
  src/dm/dm.controller.ts
  src/dm/dm.module.ts
  src/dm/dto/dm.dto.ts
  src/game/game.gateway.ts
  src/user/entity/user.otp.entity.ts
  src/user/user.controller.ts
  src/user/user.gateway.ts
  src/user/user.module.ts
Labels: Feat

#47 fix: Dm, redis 저장 값 불러 올때, 형식 누락부분 추가
  src/configs/typeorm.config.ts
  src/game/dto/game.dto.ts
  src/game/entity/game.channel.entity.ts
  src/game/entity/game.entity.ts
  src/game/entity/game.player.entity.ts
  src/game/enum/game.enum.ts
  src/game/game.gateway.ts
  src/game/game.module.ts
  src/game/game.player.service.ts
  src/game/game.service.ts
  src/user/user.gateway.ts
Labels: Feat

#48 feat: game, game play wall collision 기능 추가
  src/channel/channel.service.ts
  src/configs/typeorm.config.ts
  src/game/dto/game.dto.ts
  src/game/entity/game.entity.ts
  src/game/entity/game.player.entity.ts
  src/game/enum/game.enum.ts
  src/game/game.controller.ts
  src/game/game.gateway.ts
  src/game/game.module.ts
  src/game/game.player.service.ts
  src/game/game.service.ts
  src/main.ts
  src/middleware/session-middleware.ts
  src/user/user.gateway.ts
  src/user/user.module.ts
Labels: Feat

#50 feat: channel,game private 채널 입장 기능 추가
  src/channel/channel.gateway.ts
  src/channel/channel.service.ts
  src/game/entity/game.entity.ts
  src/game/entity/game.player.entity.ts
  src/game/game.channel.service.ts
  src/game/game.controller.ts
  src/game/game.gateway.ts
  src/game/game.module.ts
  src/game/game.player.service.ts
  src/game/game.service.ts
  src/user/user.controller.ts
  src/user/user.gateway.ts
  src/user/user.module.ts
Labels: Feat

#57 feat: 친구 상태 확인 기능 추가
  src/channel/channel.gateway.ts
  src/game/game.channel.service.ts
  src/game/game.gateway.ts
  src/user/user.gateway.ts
Labels: Feat

#58 fix: game,channel 등 소켓통신 시 안되던 부분들 수정
  src/channel/channel.gateway.ts
  src/channel/channel.service.ts
  src/game/game.channel.service.ts
  src/game/game.gateway.ts
  src/user/user.gateway.ts
Labels: Feat, fix, refactor

#59 fix: channel, 최소인원 0명에서 2명으로 변경
  src/channel/channel.service.ts
Labels: refactor

#61 fix: default 유저가 접속되던 이슈 수정
  src/channel/channel.gateway.ts
  src/game/game.channel.service.ts
  src/game/game.gateway.ts
  src/user/user.gateway.ts
Labels: Feat, fix

#63 fix: 기록 및 전적 미저장 이슈 해결
  src/game/entity/game.entity.ts
  src/game/game.channel.service.ts
  src/game/game.gateway.ts
  src/game/game.module.ts
  src/game/game.player.service.ts
  src/game/game.service.ts
  src/user/user.module.ts
Labels: fix

#64 fix: userOtpRepository 종속성 이슈 해결
  src/game/game.gateway.ts
  src/game/game.module.ts
Labels: fix

#66 fix: channel,game 새로고침 시 미접속 이슈 해결
  src/channel/channel.gateway.ts
  src/game/dto/game.dto.ts
  src/game/game.channel.service.ts
  src/game/game.gateway.ts
  src/game/game.player.service.ts
  src/game/game.service.ts
Labels: Feat, fix

#68 feat: single game 추가
  src/auth/auth.controller.ts
  src/auth/jwt/jwtUserCreation.guard.ts
  src/auth/jwt/jwtWebSocket.filter.ts
  src/channel/channel.gateway.ts
  src/channel/channel.service.ts
  src/channel/dto/channel.user.dto.ts
  src/game/dto/game.dto.ts
  src/game/enum/game.enum.ts
  src/game/game.channel.service.ts
  src/game/game.gateway.ts
  src/game/game.player.service.ts
  src/game/game.service.ts
  src/user/dto/user.profile.dto.ts
  src/user/entity/user.entity.ts
  src/user/user.controller.ts
  src/user/user.gateway.ts
  src/user/user.service.ts
Labels: Feat, fix, refactor

#69 feat: record game
  src/auth/auth.controller.ts
  src/auth/fortytwo/fortytwo.strategy.ts
  src/auth/jwt/jwtSign.guard.ts
  src/auth/jwt/jwtUserCreation.guard.ts
  src/channel/channel.gateway.ts
  src/channel/channel.service.ts
  src/channel/dto/channel.user.dto.ts
  src/channel/entity/channels.entity.ts
  src/game/dto/game.dto.ts
  src/game/entity/game.channel.entity.ts
  src/game/game.channel.service.ts
  src/game/game.gateway.ts
  src/game/game.player.service.ts
  src/game/game.service.ts
  src/user/dto/user.dto.ts
  src/user/dto/user.profile.dto.ts
  src/user/user.controller.ts
  src/user/user.gateway.ts
  src/user/user.otp.service.ts
Labels: Feat, fix

#70 refactor: game, socket 연결 끊길 때 발생하는 로직 변경
  src/channel/channel.service.ts
  src/commons/redis-client.service.ts
  src/configs/typeorm.config.ts
  src/game/game.channel.service.ts
  src/game/game.gateway.ts
  src/game/game.module.ts
  src/game/game.player.service.ts
  src/game/game.service.ts
  src/redis/redis.adapter.ts
  src/user/user.gateway.ts
Labels: Feat, fix, refactor

#72 fix: single 게임 비정상 종료 시 이슈 해결
  src/game/game.gateway.ts
  src/game/game.player.service.ts
  src/game/game.service.ts
  src/user/user.controller.ts
  src/user/user.gateway.ts
  src/user/user.service.ts
Labels: fix
